/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import java.awt.List;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import minhasClasses.Acessos;


/**
 *
 * @author Aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    java.util.List<Acessos> acesso = new ArrayList<>();
    java.util.List<String> vetData = new ArrayList<>();
    java.util.List<String> vetNavegadores = new ArrayList<>();
    java.util.List<Integer> vetQTDN = new ArrayList<>();
    java.util.List<Integer> vetQTDNa = new ArrayList<>();
    java.util.List<Integer> vetfi = new ArrayList<>();
    java.util.List<Integer> vetQTD = new ArrayList<Integer>();
    java.util.List<Integer> vetQTDRep = new ArrayList<>();
    java.util.List<Double> vetFreq = new ArrayList<>();
    java.util.List<Integer> vetxifi = new ArrayList<>();
    java.util.List<Integer> vetFi = new ArrayList<>();
    java.util.List<Double> vetFr = new ArrayList<>();
    java.util.List<Double> vetV = new ArrayList<>();
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCaminho = new javax.swing.JTextField();
        btnArquivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tArea = new javax.swing.JTextArea();
        btnListar = new javax.swing.JButton();
        btnModa = new javax.swing.JButton();
        jModa = new javax.swing.JTextField();
        btnMediana = new javax.swing.JButton();
        jMediana = new javax.swing.JTextField();
        btnDesvio = new javax.swing.JButton();
        jDesvio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tTabeladeDados = new javax.swing.JTable();
        btnSair = new javax.swing.JButton();
        btnResetar = new javax.swing.JButton();
        btnNavegadores = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tTabeladeNavegadores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnModaNavegador = new javax.swing.JButton();
        jModaNavegador = new javax.swing.JTextField();
        btnMedia = new javax.swing.JButton();
        jMedia = new javax.swing.JTextField();
        jScrollBar1 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Fabiola - Luis Henrique");

        btnArquivo.setText("Selecionar Arquivo");
        btnArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArquivoActionPerformed(evt);
            }
        });

        tArea.setColumns(20);
        tArea.setRows(5);
        jScrollPane1.setViewportView(tArea);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnModa.setText("Moda");
        btnModa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModaActionPerformed(evt);
            }
        });

        btnMediana.setText("Mediana");
        btnMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedianaActionPerformed(evt);
            }
        });

        btnDesvio.setText("Desv.Padrão");
        btnDesvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesvioActionPerformed(evt);
            }
        });

        tTabeladeDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "xi", "fi", "Fi", "fr", "Fr", "xi.fi", "(xi-Media)^2 . fi"
            }
        ));
        jScrollPane2.setViewportView(tTabeladeDados);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnResetar.setText("Resetar");
        btnResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetarActionPerformed(evt);
            }
        });

        btnNavegadores.setText("Listar Navegadores");
        btnNavegadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavegadoresActionPerformed(evt);
            }
        });

        tTabeladeNavegadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "xi", "fi"
            }
        ));
        jScrollPane3.setViewportView(tTabeladeNavegadores);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Documentação");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        btnModaNavegador.setText("Moda");
        btnModaNavegador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModaNavegadorActionPerformed(evt);
            }
        });

        btnMedia.setText("Media");
        btnMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNavegadores, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModaNavegador, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jModaNavegador, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModa, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jModa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDesvio, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesvio, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnResetar, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(jLabel1)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCaminho)
                    .addComponent(btnArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jMediana, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(btnMediana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jDesvio)
                        .addComponent(btnDesvio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnModa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jModa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jMedia)
                        .addComponent(btnMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNavegadores, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnModaNavegador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jModaNavegador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnResetar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArquivoActionPerformed
        JFileChooser filechoose = new JFileChooser();
        filechoose.setDialogTitle("Procurar Arquivo Log");
        filechoose.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Texto", "txt","csv");
        filechoose.setFileFilter(filter);
        int retorno = filechoose.showOpenDialog(this);
        
        if(retorno == JFileChooser.APPROVE_OPTION){
            
            File file = filechoose.getSelectedFile();            
            jCaminho.setText(file.getPath());
            try {
                Scanner luis = new Scanner(file);
                tArea.read( new FileReader( file.getAbsolutePath() ), null );
                
                // Adicionar Novos Acessos
                
                String linhaArquivo;
                String [] dadosAcesso;
                while(luis.hasNext()){
                  Acessos acessosLog = new Acessos();
                  linhaArquivo = luis.nextLine();
                  dadosAcesso = linhaArquivo.split(";");
                  acessosLog.setData(dadosAcesso[0]);
                  acessosLog.setHora(dadosAcesso[1]);
                  acessosLog.setSistema(dadosAcesso[2]);
                  acessosLog.setNavegador(dadosAcesso[3]);
                  acesso.add(acessosLog);
                  
                                    
                }
                 
            }catch (IOException ex) {
                System.out.println("problem accessing file"+file.getAbsolutePath());
            }
            
            
        }
    }//GEN-LAST:event_btnArquivoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        //Codigo Para ver quantas repetições teve as datas
        boolean achei;
        for(int i = 0; i<acesso.size(); i++){
            achei = false;
            for(int j = 0; j < vetData.size(); j++){
                if(acesso.get(i).getData().equalsIgnoreCase(vetData.get(j))){
                    achei = true;
                }
            }
            if(!achei){
                vetData.add(acesso.get(i).getData());
            }
        }
        int qtd;
        for(int i = 0; i < vetData.size(); i++ ){
           qtd = 0;
           for(int j = 0; j < acesso.size(); j++ ){
               if(vetData.get(i).equalsIgnoreCase(acesso.get(j).getData())){
                   qtd++;
               }
           }
           vetQTD.add(qtd);
        }
        Integer[] xi = vetQTD.toArray(new Integer[vetQTD.size()]);
        Arrays.sort(xi);
        //Codigo para ver quantas vezes o numero de repetição da data teve
        
        for(int i = 0; i<xi.length; i++){
            achei = false;
            for(int j = 0; j < vetQTDN.size(); j++){
                if(xi[i] == vetQTDN.get(j)){
                    achei = true;
                }
            }
            if(!achei){
                vetQTDN.add(xi[i]);
            }
        }
        for(int i = 0; i < vetQTDN.size(); i++ ){
           qtd = 0;
           for(int j = 0; j < xi.length; j++ ){
               if(vetQTDN.get(i) == xi[j]){
                   qtd++;
               }
           }
           vetfi.add(qtd);
        }
        double frequencia;
        int valor = 0;
        int so = 0;
        for (int i = 0; i < vetfi.size(); i++) {
           valor = vetfi.get(i);
           so = so+valor;
        }
        for (int i = 0; i < vetfi.size(); i++) {
            frequencia = vetfi.get(i)*100 / (double)so;
            vetFreq.add(frequencia);
        }
        
        //Calculo do xi.fi
        int resultado;
        for (int i = 0; i < vetQTDN.size(); i++) {
            resultado = vetQTDN.get(i) * vetfi.get(i);
            vetxifi.add(resultado);
        }
        
        //Calculo do Fi
        int primeiro = 0;
        int numeros;
        for (int i = 0; i < vetfi.size(); i++) {
            numeros = primeiro + vetfi.get(i);
            primeiro = numeros;
            vetFi.add(numeros);
        }
        
        //Calculo do Fr
        double prime = 0;
        double resto = 0;
        for (int i = 0; i < vetFreq.size(); i++) {
            resto = prime + vetFreq.get(i);
            prime = resto;
            vetFr.add(resto);
        }
        
        //Calculo da Media
        
        int soma1 = 0,so1 = 0;
        double media;
        for (int i = 0; i < vetxifi.size(); i++) {
            soma1 = soma1 + vetxifi.get(i);
            so1 = so1+vetfi.get(i);
        }
        media = (double)soma1 / so1;
        
        //Calcular o (xi-Media)^2.fi
        
        double mult = 0;
        for (int i = 0; i < vetfi.size(); i++) {
            mult = Math.pow(vetQTDN.get(i) - media, 2)*vetfi.get(i);
            vetV.add(mult);
        }        
        for (int i = 0; i < vetQTDN.size(); i++) {
            DefaultTableModel tabela = (DefaultTableModel) tTabeladeDados.getModel();
            tabela.addRow(new String[] {String.valueOf(vetQTDN.get(i)),String.valueOf(vetfi.get(i)),String.valueOf(vetFi.get(i)),String.format("%.2f", vetFreq.get(i))+ String.valueOf("%"),String.format("%.2f", vetFr.get(i))+ String.valueOf("%"),String.valueOf(vetxifi.get(i)),String.format("%.2f", vetV.get(i))});
        }
        
        
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnModaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModaActionPerformed
        int maior = 0;
        int xi = 0;
        for (int i = 0; i < vetfi.size(); i++) {
            if(vetfi.get(i) > maior ){
                maior = vetfi.get(i);
                xi = vetQTDN.get(i);
            }
        }
        jModa.setText(String.valueOf(xi));
    }//GEN-LAST:event_btnModaActionPerformed

    private void btnNavegadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavegadoresActionPerformed
        //Codigo Para ver quantas repetições teve as datas
        boolean achei;
        for(int i = 0; i<acesso.size(); i++){
            achei = false;
            for(int j = 0; j < vetNavegadores.size(); j++){
                if(acesso.get(i).getNavegador().equalsIgnoreCase(vetNavegadores.get(j))){
                    achei = true;
                }
            }
            if(!achei){
                vetNavegadores.add(acesso.get(i).getNavegador());
            }
        }
        int qtd;
        for(int i = 0; i < vetNavegadores.size(); i++ ){
           qtd = 0;
           for(int j = 0; j < acesso.size(); j++ ){
               if(vetNavegadores.get(i).equalsIgnoreCase(acesso.get(j).getNavegador())){
                   qtd++;
               }
           }
           vetQTDNa.add(qtd);
        }
        for (int i = 0; i < vetNavegadores.size(); i++) {
            DefaultTableModel tabela = (DefaultTableModel) tTabeladeNavegadores.getModel();
            tabela.addRow(new String[] {vetNavegadores.get(i),String.valueOf(vetQTDNa.get(i))});
        }
    }//GEN-LAST:event_btnNavegadoresActionPerformed

    private void btnModaNavegadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModaNavegadorActionPerformed
        String navegador = null;
        int maior = -1;
        for (int i = 0; i < vetQTDNa.size(); i++) {
            if(vetQTDNa.get(i) > maior ){
                maior = vetQTDNa.get(i);
                navegador = vetNavegadores.get(i);
            }
        }
        jModaNavegador.setText(String.valueOf(navegador));
    }//GEN-LAST:event_btnModaNavegadorActionPerformed

    private void btnMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaActionPerformed
        int soma = 0,so = 0;
        double media;
        for (int i = 0; i < vetxifi.size(); i++) {
            soma = soma + vetxifi.get(i);
            so = so+vetfi.get(i);
        }
        media = (double)soma / so;
        jMedia.setText(String.format("%.2f", media));
        
    }//GEN-LAST:event_btnMediaActionPerformed

    private void btnDesvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesvioActionPerformed
        
        //Calculo da Variança
        double soma = 0,vari;
        int so = 0;
        for (int i = 0; i < vetV.size(); i++) {
            soma = soma + vetV.get(i);
            so = so+vetfi.get(i);
        }
        vari = soma / so;
        
        //Calculo do desvio padrão
        double desvio;
        desvio = Math.sqrt(vari);
        jDesvio.setText(String.format("%.2f", desvio));
    }//GEN-LAST:event_btnDesvioActionPerformed

    private void btnMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedianaActionPerformed
        int resu;
        int posi = 0;
        if(vetQTDN.size() % 2 != 0){
            posi = ((vetQTDN.size()+1)/2);
            resu = vetQTDN.get(posi-1);
        }else{
            posi = Math.round((vetQTDN.size()+1)/2)-1;
            resu = (vetQTDN.get(posi)+vetQTDN.get(posi+1))/2;
        }
        jMediana.setText(String.valueOf(resu));
    }//GEN-LAST:event_btnMedianaActionPerformed

    private void btnResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetarActionPerformed
        DefaultTableModel tabela = (DefaultTableModel) tTabeladeDados.getModel();
        tabela.setNumRows(0);
        DefaultTableModel tabela1 = (DefaultTableModel) tTabeladeNavegadores.getModel();
        tabela1.setNumRows(0);
        jCaminho.setText("");
        jDesvio.setText("");
        jMedia.setText("");
        jMediana.setText("");
        jModa.setText("");
        jModaNavegador.setText("");
        tArea.setText("");
        acesso.clear();
        vetData.clear();
        vetFi.clear();
        vetFr.clear();
        vetFreq.clear();
        vetNavegadores.clear();
        vetQTD.clear();
        vetQTDN.clear();
        vetQTDNa.clear();
        vetQTDRep.clear();
        vetV.clear();
        vetfi.clear();
        vetxifi.clear();
    }//GEN-LAST:event_btnResetarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArquivo;
    private javax.swing.JButton btnDesvio;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnMedia;
    private javax.swing.JButton btnMediana;
    private javax.swing.JButton btnModa;
    private javax.swing.JButton btnModaNavegador;
    private javax.swing.JButton btnNavegadores;
    private javax.swing.JButton btnResetar;
    private javax.swing.JButton btnSair;
    private javax.swing.JTextField jCaminho;
    private javax.swing.JTextField jDesvio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jMedia;
    private javax.swing.JTextField jMediana;
    private javax.swing.JTextField jModa;
    private javax.swing.JTextField jModaNavegador;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea tArea;
    private javax.swing.JTable tTabeladeDados;
    private javax.swing.JTable tTabeladeNavegadores;
    // End of variables declaration//GEN-END:variables
}
